<%@ taglib uri="/struts-tags" prefix="s"%>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js">
</script>

<table border = "0">
	<tr><th colspan="7" class="mainheading">PROCEDURE FOR E-FILING</th></tr>
		<tr class="subheading">
			<td colspan="7">Step 1: Preparation of the Petition offline:</td>			
		</tr>
		<tr>
			<td></td>
			<td>1.1 </td>
			<td colspan="5">
				The original text material, documents, additional information, main petition, as the case may be, and interlocutory applications etc. will be prepared electronically using MS Word or Open Office software. The formatting style of the text will be as under:
					<table>
						<tr><td width="5%"></td><td width="10%">Paper size </td><td width="85%">A-4</td></tr>
						<tr><td></td><td>Margins </td><td>Top : 1.5</td></tr>
						<tr><td></td><td></td><td>Bottom : 1.5</td></tr>
						<tr><td></td><td></td><td>Left : 2.54</td></tr>
						<tr><td></td><td>Justification</td><td>Full</td></tr>
						<tr><td></td><td>Font</td><td>Times New Roman</td></tr>
						<tr><td></td><td>Font Size</td><td>12</td></tr>
						<tr><td></td><td>Line spacing</td><td>1.5</td></tr>
					</table>
			</td>
		</tr>
		<tr>
			<td></td>
			<td>1.2 </td>
			<td colspan="5">
				The documents should be converted into Portable Document Format (PDF) using any PDF converter or in-built PDF conversion plug-in provided in the software.
			</td>
		</tr>
		<tr>
			<td></td>
			<td>1.3 </td>
			<td colspan="5">
				Where the document is not a text document and has to be enclosed with the petition, appeal or application or other pleadings, the document should be scanned using an image resolution of 300 dpi (dot per inch) and saved as a PDF document.
			</td>
		</tr>
		<tr>
			<td></td>
			<td>1.4 </td>
			<td colspan="5">
				At a single form submit total size of the files uploaded should not exceed 100 MB. If files to be uploaded are more than mentioned size, then the same can be uploaded in different iterations
			</td>
		</tr>
		<tr>
			<td></td>
			<td>1.5 </td>
			<td colspan="5">
				The text documents prepared in MS Word/Open Office as well as scanned documents should be merged as a single PDF file and bookmarked as per the index of the petition.  PDFSam is free and open source software for merging and splitting PDF documents.
			</td>
		</tr>
		<tr>
			<td></td>
			<td>1.6 </td>
			<td colspan="5">
				The merged documents should be uploaded at the time of e-filing. The screen shots of the manner of accessing the e-filing portal and filling up the relevant columns for the purpose of e-filing are set out in e-Filing user manual/ video tutorials.
			</td>
		</tr>
		
	</table>	
	<table border = "0">
		<tr class="subheading">
			<td colspan="7">Step 2: Online Filing the Petition on MERC e-Filing Portal:</td> 			
		</tr>
		<tr>
			<td></td>
			<td>2.1 </td>
			<td colspan="5">
				 The e-Filing portal can be accessed by clicking on the hyperlink E-filing placed at the bottom of the web site www.merc.gov.in or on the link Petition e-filing on the left tab after registration by entering login credentials. 
				 The stakeholders learned Counsels/Advocate can register them on MERC e-Filing portal by clicking E-Registration (New User). User account once created can be used in future by the party or the lawyer. Please refer e-Registration user manual/ video tutorials.
			</td>
		</tr>
		<tr>
			<td></td>
			<td>2.2 </td>
			<td colspan="5">
				After successful login, fill in all the details of the petitions on the General Information form. On saving this form a Reference Number will be generated and other forms like Respondent Details, Related Petitions, Identical Petitions, Asset Details, Attachments, and Summary etc. will be displayed. Then upload all the files/documents related to petition fee is automatically calculated through system. The total Petition/Application fee is payable through RTGS / NEFT only. The screen shots of the manner of accessing the e-filing portal and filling up the relevant columns for the purpose of e-filing are set out in e-Filing user manual/ video tutorials.
			</td>
		</tr>
		<tr>
			<td></td>
			<td>2.3 </td>
			<td colspan="5">
				Finally, after submission of Petition a diary number is generated by the system against the petition filed. An email confirming the same will be send to the users registered email id.
			</td>
		</tr>
		<tr>
			<td></td>
			<td>2.4 </td>
			<td colspan="5">
				Take the print out of Summary Sheet, Form1 (Payment related) from the e-Filing reports & summary section and submit it at Maharashtra Registry along with the hardcopies as per the current system of filing hard copies of petitions in terms of the provisions of the MERC (Conduct of Business) Regulations, 1999, as amended from time to time in addition to the above.
			</td>
		</tr>
		<tr>
			<td></td>
			<td>2.5 </td>
			<td colspan="5">
				The documents uploaded by the petitioner are visible to MERC and respondents filled by the petitioner at the time of filling petition except the Vakalatnama.
			</td>
		</tr>
		<tr>
			<td></td>
			<td>2.6 </td>
			<td colspan="5">
				The petition filed by the parties or lawyers are scrutinized by MERC registry and in case a defect is found the notification of the same is sent via email to one who has filed the petition. The petitioner can also see the defects in their respective interface also.
			</td>
		</tr>
		<tr>
			<td></td>
			<td>2.7 </td>
			<td colspan="5">
				Corresponding to any deficiency notified, the party or lawyer may rectify the defect and upload the fresh document / petition through their interface.
			</td>
		</tr>	
		<tr>
			<td></td>
			<td>2.8 </td>
			<td colspan="5">
				If no deficiency is found the petition is registered and notification via email is sent to the petitioner.
			</td>
		</tr>		
		<tr><td colspan="7"></td></tr>
	</table>
	<table border = "0">
		<tr class="subheading">
			<td colspan="7">Step 3: Online Filing of replies/ rejoinders/written submission/additional information etc regarding Petition on MERC e-Filing Portal:</td> 		
		</tr>
		<tr>
			<td></td>
			<td>3.1 </td>
			<td colspan="5">
				After login, the e-filing portal permits the user to upload the pleading documents pertaining to any particular petition. Petition-wise search is permitted to upload the documents pertaining to any particular case.
			</td>
		</tr>
		<tr>
			<td></td>
			<td>3.2 </td>
			<td colspan="5">
				Pleadings link on the menu is provided to file the documents associated with the already filed petitions. Important data like petition number, subject, and petition status as per the MERC database of already filed petitions prior to 4.4.2016 have been migrated in the eFilling application for uploading the pleading documents which are not filed through e-Filing portal. Please note that MERC has made all endeavour to migrate updated, correct and accurate information however, MERC shall be obliged if errors/omissions are brought to its notice for carrying out corrections. Users are also advised to verify the correctness of the information from the records of the Commission. Please refer e-Pleading user manual/ video tutorials for more details.
			</td>
		</tr>	
		<tr>
			<td></td>
			<td>3.3 </td>
			<td colspan="5">
				The documents uploaded by the petitioner are visible to MERC and respondents filled by the petitioner at the time of filling petition through e-Filing portal. Please note that pleadings documents uploaded for the petitions not filed through e-Filing portal or migrated petitions shall be visible to petitioner and MERC only and not to respondents. Hence Stakeholders are also requested to add respondents to the migrated petitions.
			</td>
		</tr>		
		<tr><td colspan="7"></td></tr>
	</table>
	<table border = "0">
		<tr class="subheading">
			<td colspan="7">Step 4: For more details please refer FAQ (frequently asked questions) section. Assistance will be extended to the parties to file the petitions online through the helpdesk available with the registry of the Commission.</td>			
		</tr>
		<tr><td colspan="7"></td></tr>
	</table>
	<table border = "0">
		<tr class="subheading">
			<td colspan="7">Step 5: For all technical errors, queries, training slots dates, feedback, suggestions etc. Please contact/write/mail to:</td>			
		</tr>
		<tr class='white_td'>
			<td colspan="7" align="center">
			Maharashtra Electricity Regulatory Commission,<br/><br/>
			 World Trade Centre,Centre No.1,<br/>
 13th Floor,Cuffe Parade,<br/>
 Colaba, Mumbai-400005<br/><br/>
 Ph: 091-22-22163964/65/69<br/>
 Fax: 091-22-22163976<br/><br/>
 e-mail : mercindia@merc.gov.in</td>

		</tr>	
		<tr><td colspan="7"></td></tr>
		<tr>
		<td colspan="7" align="right">
		<s:a href="/merc/"><input type="button" id="cancelbutton" name="cancelbutton" value="Cancel" class="formbutton"/></s:a>
		</td>
		</tr>
	</table>

	<%-- <table border = "0">
		<tr><th colspan="7" class="mainheading">About Us - Roll Out Plan</th></tr>
		<tr class="subheading">
			<td colspan="2">Date</td>
			<td colspan="5">Strategy/Plan</td>			
		</tr>
		<tr class='white_td'>
			<td colspan="2">29.10.2015<br/>Onwards</td>
			<td colspan="5">Stakeholders, Advocates, Organizations, Organization Employees etc  will register online through e-Registration module</td>			
		</tr>
		<tr class='colored_td'>
			<td colspan="2">16.11.2015<br/>to<br/>15.12.2015</td>
			<td colspan="5">Trial run of e-Filing/e-Pleading module in which registered stakeholders will file their petitions, reply, rejoinders etc online</td>			
		</tr>
		<tr class='white_td'>
			<td colspan="2">15.12.2015<br/>to<br/>31.12.2015</td>
			<td colspan="5">Incorporating suggestions/changes and finalization of user manuals etc by MERC</td> 			
		</tr>
		<tr class='colored_td'>
			<td colspan="2">01.01.2016<br/>Onwards<br/>(Tentative)</td>
			<td colspan="5">Final Launch of e-Filing , Both online e-Filing and current method of filing petitions will run in parallel for at least 3-6 months till the stakeholders are used to e-File their petitions, reply, rejoinders etc.</td>			
		</tr>
		<tr><td colspan="7"></td></tr>
		<tr>
		<td colspan="7" align="right">
			<s:a href="/merc/"><input type="button" id="cancelbutton" name="cancelbutton" value="Cancel" class="formbutton"/></s:a>
		</td>
		</tr>
	</table> --%>
	<s:token/>

            	